package br.pucminas.sige.demandtypes.application;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class DynamicFieldValidatorTest {
  @Test void validatesNumberRange(){String d="[{\"name\":\"budget\",\"type\":\"NUMBER\",\"required\":true,\"validation\":{\"min\":0,\"max\":100}}]";assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("budget","10.50"),Set.of()));for(String value:List.of("-1","101","abc","NaN"))assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("budget",value),Set.of()));}
  @Test void validatesDateAndSelection(){String d="[{\"name\":\"day\",\"type\":\"DATE\",\"validation\":{\"minDate\":\"2026-01-01\"}},{\"name\":\"option\",\"type\":\"SELECT\",\"options\":[\"A\",\"B\"]}]";assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("day","2025-12-31"),Set.of()));assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("day","2026-02-30"),Set.of()));assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("option","C"),Set.of()));assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("day","2026-01-01","option","B"),Set.of()));}
  @Test void requiresConditionalFieldOnlyWhenConditionMatches(){String d="[{\"name\":\"mode\"},{\"name\":\"reason\",\"requiredWhen\":{\"field\":\"mode\",\"equals\":\"urgent\"}}]";assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("mode","normal"),Set.of()));assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("mode","urgent"),Set.of()));assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("mode","urgent","reason","Prazo"),Set.of()));}
  @Test void doesNotAcceptFileNameWithoutUpload(){String d="[{\"name\":\"brief\",\"type\":\"FILE\",\"required\":true}]";assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("brief","arquivo.pdf"),Set.of()));assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("brief","arquivo.pdf"),Set.of("brief")));}
  @Test void rejectsInvalidConfigurationAndUnknownValues(){for(String d:List.of("{}","[{\"name\":\"a\",\"type\":\"OTHER\"}]","[{\"name\":\"a\",\"type\":\"SELECT\",\"options\":[]}]","[{\"name\":\"a\",\"requiredWhen\":{\"field\":\"missing\",\"equals\":\"yes\"}}]"))assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.definitions(d));assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate("[]",Map.of("extra","value"),Set.of()));}
  @Test void validatesTextLength(){String d="[{\"name\":\"text\",\"validation\":{\"minLength\":3,\"maxLength\":5}}]";assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("text","ab"),Set.of()));assertThrows(IllegalArgumentException.class,()->DynamicFieldValidator.validate(d,Map.of("text","abcdef"),Set.of()));assertDoesNotThrow(()->DynamicFieldValidator.validate(d,Map.of("text","abcd"),Set.of()));}
}
