package br.pucminas.sige.reference.api;

import br.pucminas.sige.campaigns.domain.CampaignRepository;
import br.pucminas.sige.clients.domain.ClientRepository;
import br.pucminas.sige.demandtypes.domain.DemandTypeRepository;
import br.pucminas.sige.shared.domain.Role;
import br.pucminas.sige.shared.security.CurrentUser;
import br.pucminas.sige.users.domain.AppUserRepository;
import java.util.List;
import org.springframework.web.bind.annotation.*;

@org.springframework.transaction.annotation.Transactional(readOnly=true)
@RestController @RequestMapping("/api/v1/reference")
public class ReferenceController {
  private final ClientRepository clients; private final CampaignRepository campaigns; private final DemandTypeRepository demandTypes; private final AppUserRepository users; private final CurrentUser current;private final br.pucminas.sige.tickets.application.TicketAccessPolicy access;
  public ReferenceController(ClientRepository clients,CampaignRepository campaigns,DemandTypeRepository demandTypes,AppUserRepository users,CurrentUser current,br.pucminas.sige.tickets.application.TicketAccessPolicy access){this.clients=clients;this.campaigns=campaigns;this.demandTypes=demandTypes;this.users=users;this.current=current;this.access=access;}
  record Option(String id,String label){} record CampaignItem(String id,String clientId,String name,String channel,String objective){} record DemandTypeItem(String id,String name,boolean approvalRequired,boolean evidenceRequired,String fieldDefinitions){} record UserItem(String id,String name,String role,String clientId){} record Response(List<Option> clients,List<CampaignItem> campaigns,List<DemandTypeItem> demandTypes,List<UserItem> trafficManagers,List<UserItem> clientUsers){}
  @GetMapping public Response all(){var actor=current.require();var visible=access.visibleTickets(actor);boolean limited=actor.getRole()==Role.TRAFFIC_MANAGER;var visibleClients=visible.stream().map(ticket->ticket.getClient().getId()).collect(java.util.stream.Collectors.toSet());var visibleCampaigns=visible.stream().filter(ticket->ticket.getCampaign()!=null).map(ticket->ticket.getCampaign().getId()).collect(java.util.stream.Collectors.toSet());var visibleManagers=visible.stream().filter(ticket->ticket.getAssignee()!=null).map(ticket->ticket.getAssignee().getId()).collect(java.util.stream.Collectors.toSet());var clientOptions=(actor.getRole()==Role.CLIENT?List.of(actor.getClient()):clients.findAll()).stream().filter(br.pucminas.sige.clients.domain.Client::isActive).filter(client->!limited||visibleClients.contains(client.getId())).map(client->new Option(client.getId().toString(),client.getName())).toList();var campaignItems=(actor.getRole()==Role.CLIENT?campaigns.findByClientIdAndActiveTrueOrderByName(actor.getClient().getId()):campaigns.findAll().stream().filter(br.pucminas.sige.campaigns.domain.Campaign::isActive).toList()).stream().filter(campaign->!limited||visibleCampaigns.contains(campaign.getId())).map(campaign->new CampaignItem(campaign.getId().toString(),campaign.getClient().getId().toString(),campaign.getName(),campaign.getChannel(),campaign.getObjective())).toList();var types=demandTypes.findAll().stream().filter(br.pucminas.sige.demandtypes.domain.DemandType::isActive).map(type->new DemandTypeItem(type.getId().toString(),type.getName(),type.isApprovalRequired(),type.isEvidenceRequired(),type.getFieldDefinitions())).toList();var traffic=users.findByRoleInAndActiveTrue(List.of(Role.TRAFFIC_MANAGER)).stream().filter(user->limited?user.getId().equals(actor.getId()):actor.getRole()!=Role.CLIENT||visibleManagers.contains(user.getId())).map(user->new UserItem(user.getId().toString(),user.getName(),user.getRole().name(),null)).toList();var clientUsers=actor.getRole()==Role.CLIENT?List.of(new UserItem(actor.getId().toString(),actor.getName(),actor.getRole().name(),actor.getClient().getId().toString())):limited?List.<UserItem>of():users.findByRoleAndActiveTrue(Role.CLIENT).stream().map(user->new UserItem(user.getId().toString(),user.getName(),user.getRole().name(),user.getClient().getId().toString())).toList();return new Response(clientOptions,campaignItems,types,traffic,clientUsers);}
}
