package br.pucminas.sige.tickets.application;

import br.pucminas.sige.campaigns.domain.*;
import br.pucminas.sige.clients.domain.*;
import br.pucminas.sige.demandtypes.domain.*;
import br.pucminas.sige.notifications.application.NotificationService;
import br.pucminas.sige.shared.domain.*;
import br.pucminas.sige.shared.security.CurrentUser;
import br.pucminas.sige.sla.application.SlaService;
import br.pucminas.sige.tickets.api.TicketDtos;
import br.pucminas.sige.tickets.domain.*;
import br.pucminas.sige.users.domain.*;
import br.pucminas.sige.files.domain.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.*;
import java.util.stream.*;
import java.time.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service @Transactional
public class TicketService {
  private final TicketRepository tickets; private final ClientRepository clients; private final CampaignRepository campaigns; private final DemandTypeRepository demandTypes; private final AppUserRepository users; private final TicketHistoryRepository history; private final TicketCommentRepository comments; private final TicketAttachmentRepository attachments; private final TicketNumberGenerator numbers; private final SlaService sla; private final NotificationService notifications; private final CurrentUser current; private final TicketAccessPolicy access; private final ObjectMapper json;
  public TicketService(TicketRepository tickets, ClientRepository clients, CampaignRepository campaigns, DemandTypeRepository demandTypes, AppUserRepository users, TicketHistoryRepository history, TicketCommentRepository comments, TicketAttachmentRepository attachments, TicketNumberGenerator numbers, SlaService sla, NotificationService notifications, CurrentUser current, TicketAccessPolicy access, ObjectMapper json) { this.tickets=tickets; this.clients=clients; this.campaigns=campaigns; this.demandTypes=demandTypes; this.users=users; this.history=history; this.comments=comments; this.attachments=attachments; this.numbers=numbers; this.sla=sla; this.notifications=notifications; this.current=current; this.access=access; this.json=json; }
  public TicketDtos.TicketList list(String search,TicketStatus status,UUID clientId,UUID campaignId,UUID demandTypeId,Priority priority,UUID assigneeId,LocalDate createdFrom,LocalDate createdTo,int page,int size){return list(search,status,clientId,campaignId,demandTypeId,priority,assigneeId,createdFrom,createdTo,page,size,null);}
  public TicketDtos.TicketList list(String search,TicketStatus status,UUID clientId,UUID campaignId,UUID demandTypeId,Priority priority,UUID assigneeId,LocalDate createdFrom,LocalDate createdTo,int page,int size,Boolean onlyOverdue){if(page<0||size<1||size>100)throw new IllegalArgumentException("Paginação inválida");var result=tickets.findAll(TicketQuery.filters(current.require(),search,status,clientId,campaignId,demandTypeId,priority,assigneeId,createdFrom,createdTo,onlyOverdue),org.springframework.data.domain.PageRequest.of(page,size,org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Order.desc("updatedAt"),org.springframework.data.domain.Sort.Order.asc("id"))));return new TicketDtos.TicketList(result.getContent().stream().map(this::item).toList(),result.getTotalElements(),page,size);}
  public TicketDtos.TicketReport report(String search, TicketStatus status, UUID clientId, UUID campaignId, UUID demandTypeId, Priority priority, UUID assigneeId, LocalDate createdFrom, LocalDate createdTo) {return report(search,status,clientId,campaignId,demandTypeId,priority,assigneeId,createdFrom,createdTo,null);}
  public TicketDtos.TicketReport report(String search, TicketStatus status, UUID clientId, UUID campaignId, UUID demandTypeId, Priority priority, UUID assigneeId, LocalDate createdFrom, LocalDate createdTo,Boolean onlyOverdue) { List<Ticket> matches=tickets.findAll(TicketQuery.filters(current.require(),search,status,clientId,campaignId,demandTypeId,priority,assigneeId,createdFrom,createdTo,onlyOverdue),org.springframework.data.domain.Sort.by("updatedAt").descending()); Instant now=Instant.now(); long active=matches.stream().filter(ticket->ticket.getStatus()!=TicketStatus.DONE&&ticket.getStatus()!=TicketStatus.CANCELLED).count(); long completed=matches.stream().filter(ticket->ticket.getStatus()==TicketStatus.DONE).count(); List<Ticket> classified=matches.stream().filter(ticket->ticket.getResolutionDueAt()!=null&&ticket.getStatus()!=TicketStatus.CANCELLED).toList(); long overdue=classified.stream().filter(ticket->overdue(ticket,now)).count(); long compliant=classified.size()-overdue; List<Long> durations=matches.stream().filter(ticket->ticket.getCompletedAt()!=null).map(ticket->Duration.between(ticket.getCreatedAt(),ticket.getCompletedAt()).toMinutes()).toList(); Long average=durations.isEmpty()?null:Math.round(durations.stream().mapToLong(Long::longValue).average().orElse(0)); List<TicketDtos.TicketItem> items=matches.stream().map(this::item).toList(); return new TicketDtos.TicketReport(items,items.size(),new TicketDtos.ReportSummary(active,completed,classified.size(),compliant,overdue,average)); }
  private boolean overdue(Ticket ticket, Instant now) { return "OVERDUE".equals(SlaService.responseState(ticket,now))||"OVERDUE".equals(SlaService.resolutionState(ticket,now)); }
  public TicketDtos.TicketDetail detail(UUID id) { Ticket ticket=requiredTicket(id); return new TicketDtos.TicketDetail(item(ticket),ticket.getDescription(),ticket.getPendingCampaign(),ticket.getDesiredDate(),ticket.getRequester().getName(),ticket.getAuthor().getName(),SlaService.state(ticket,Instant.now()),ticket.getResponseDueAt(),ticket.getResolutionDueAt(),ticket.getResolutionCycle(),ticket.getWaitOrigin()==null?null:ticket.getWaitOrigin().name(),ticket.getWaitReason(),ticket.isComplementReceived(),ticket.getMetrics(),comments.findByTicketIdOrderByCreatedAtAsc(id).stream().map(comment -> new TicketDtos.TicketCommentItem(comment.getId().toString(),comment.getAuthor().getName(),comment.getBody(),comment.isEffectiveResponse(),comment.getCreatedAt())).toList(),attachments.findByTicketIdOrderByCreatedAtAsc(id).stream().map(attachment -> new TicketDtos.AttachmentItem(attachment.getId().toString(),attachment.getOriginalName(),attachment.getContentType(),attachment.getSizeBytes(),attachment.getKind().name(),attachment.getEvidenceDescription(),attachment.getEvidenceUrl(),attachment.getCreatedAt())).toList(),history.findByTicketIdOrderByCreatedAtDesc(id).stream().map(entry -> new TicketDtos.TicketHistoryItem(entry.getId().toString(),entry.getActor()==null?"Sistema":entry.getActor().getName(),entry.getAction(),entry.getFieldName(),entry.getOldValue(),entry.getNewValue(),entry.getReason(),entry.getCreatedAt())).toList(),ticket.getChannel(),ticket.getResponseCompletedAt(),SlaService.responseState(ticket,Instant.now()),SlaService.resolutionState(ticket,Instant.now()),sla.elapsedBusinessMinutes(ticket,Instant.now()),fieldLabels(ticket)); }
  public TicketDtos.TicketItem create(TicketDtos.CreateTicketRequest request) {return create(request,Set.of());}
  public TicketDtos.TicketItem create(TicketDtos.CreateTicketRequest request,Set<String> suppliedFileFields) {
    AppUser actor=current.require(); requireRole(actor,Role.CLIENT,Role.SERVICE,Role.ADMIN);
    Client client=clients.findById(UUID.fromString(request.clientId())).filter(Client::isActive).orElseThrow(() -> new IllegalArgumentException("Cliente indisponível"));
    if(actor.getRole()==Role.CLIENT&&!client.getId().equals(actor.getClient().getId())) throw new org.springframework.security.access.AccessDeniedException("Ação não permitida");
    DemandType type=demandTypes.findById(UUID.fromString(request.demandTypeId())).filter(DemandType::isActive).orElseThrow(() -> new IllegalArgumentException("Tipo de demanda indisponível"));
    Campaign campaign=campaign(request.campaignId(),client);
    if(campaign==null&&(request.pendingCampaign()==null||request.pendingCampaign().isBlank())) throw new IllegalArgumentException("Informe uma campanha ou sua identificação");
    AppUser requester=requesterFor(actor,request.requesterId(),client);
    br.pucminas.sige.demandtypes.application.DynamicFieldValidator.validate(type.getFieldDefinitions(),request.metrics()==null||request.metrics().fields()==null?Map.of():request.metrics().fields(),suppliedFileFields); Ticket ticket=new Ticket(numbers.next(),client,campaign,request.pendingCampaign(),type,request.channel(),request.subject(),request.description(),request.urgency(),request.desiredDate(),requester,actor,metrics(request.metrics()));
    tickets.save(ticket); audit(ticket,actor,"TICKET_CREATED",null,null,"\"OPEN\"","Solicitação registrada"); notifications.publish(ticket,"TICKET_CREATED",ticket.getNumber()+" foi aberto."); return item(ticket);
  }
  public TicketDtos.TicketItem startTriage(UUID id, TicketDtos.StartTriageRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireRole(actor,Role.SERVICE,Role.ADMIN); TicketStatus old=ticket.getStatus(); ticket.startTriage(); audit(ticket,actor,"TRIAGE_STARTED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"TRIAGE_STARTED",ticket.getNumber()+" está em triagem."); return item(ticket); }
  public TicketDtos.TicketItem triage(UUID id, TicketDtos.TriageRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireRole(actor,Role.SERVICE,Role.ADMIN); AppUser assignee=users.findById(UUID.fromString(request.assigneeId())).filter(user -> user.isActive()&&user.getRole()==Role.TRAFFIC_MANAGER).orElseThrow(() -> new IllegalArgumentException("Responsável inválido")); Campaign campaign=campaign(request.campaignId(),ticket.getClient()); DemandType type=demandTypes.findById(UUID.fromString(request.demandTypeId())).filter(DemandType::isActive).orElseThrow(() -> new IllegalArgumentException("Tipo de demanda indisponível")); String previousPriority=json(ticket.getPriority()); String previousAssignee=ticket.getAssignee()==null?null:json(ticket.getAssignee().getId()); String previousResponseDue=json(ticket.getResponseDueAt()); String previousResolutionDue=json(ticket.getResolutionDueAt()); String previousCampaign=ticket.getCampaign()==null?null:json(ticket.getCampaign().getId()); String previousType=json(ticket.getDemandType().getId()); ticket.updateClassificationReferences(campaign,type); SlaService.Calculation calculation=sla.calculate(ticket,request.priority()); ticket.classify(request.priority(),assignee,calculation.snapshot(),calculation.responseDueAt(),calculation.resolutionDueAt()); TicketComment response=new TicketComment(ticket,actor,request.effectiveResponse(),true); comments.save(response); ticket.markEffectiveResponse(); audit(ticket,actor,"TRIAGE_CAMPAIGN","campaignId",previousCampaign,json(campaign.getId()),"Campanha confirmada na triagem"); audit(ticket,actor,"TRIAGE_TYPE","demandTypeId",previousType,json(type.getId()),"Tipo de demanda confirmado na triagem"); audit(ticket,actor,"TRIAGE_CLASSIFIED","priority",previousPriority,json(request.priority()),"Prioridade confirmada"); audit(ticket,actor,"ASSIGNEE_CHANGED","assigneeId",previousAssignee,json(assignee.getId()),"Responsável confirmado"); audit(ticket,actor,"RESPONSE_DEADLINE_CHANGED","responseDueAt",previousResponseDue,json(ticket.getResponseDueAt()),"Prazo de primeira resposta aplicado"); audit(ticket,actor,"RESOLUTION_DEADLINE_CHANGED","resolutionDueAt",previousResolutionDue,json(ticket.getResolutionDueAt()),"Prazo de resolução aplicado"); if(request.sendToExecution()) { TicketStatus old=ticket.getStatus(); ticket.sendToExecution(); audit(ticket,actor,"SENT_TO_EXECUTION","status",json(old),json(ticket.getStatus()),"Triagem concluída"); notifications.publish(ticket,"ASSIGNED",ticket.getNumber()+" foi atribuído a você."); } return item(ticket); }
  public TicketDtos.TicketItem waitForComplement(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); WaitOrigin origin=ticket.getStatus()==TicketStatus.TRIAGE?WaitOrigin.TRIAGE:WaitOrigin.EXECUTION; if(origin==WaitOrigin.TRIAGE) requireRole(actor,Role.SERVICE,Role.ADMIN); else requireExecutionActor(ticket,actor); TicketStatus old=ticket.getStatus(); ticket.waitForClient(origin,request.reason()); audit(ticket,actor,"COMPLEMENT_REQUESTED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"WAITING_FOR_CLIENT",ticket.getNumber()+" precisa de informações complementares."); return item(ticket); }
  public TicketDtos.TicketItem receiveComplement(UUID id, TicketDtos.CommentRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); if(actor.getRole()!=Role.CLIENT||actor.getClient()==null||!actor.getClient().getId().equals(ticket.getClient().getId())) throw new org.springframework.security.access.AccessDeniedException("Ação não permitida"); ticket.receiveComplement(); comments.save(new TicketComment(ticket,actor,request.body(),false)); audit(ticket,actor,"COMPLEMENT_RECEIVED",null,null,null,"Complemento enviado"); notifications.publish(ticket,"COMPLEMENT_RECEIVED",ticket.getNumber()+" recebeu complemento e aguarda conferência."); return item(ticket); }
  public TicketDtos.TicketItem resume(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireRole(actor,Role.SERVICE,Role.ADMIN); TicketStatus old=ticket.getStatus(); if(ticket.getWaitOrigin()==WaitOrigin.EXECUTION&&(ticket.getAssignee()==null||!ticket.getAssignee().isActive()||ticket.getAssignee().getRole()!=Role.TRAFFIC_MANAGER))throw new IllegalStateException("Confirme um responsável ativo antes da retomada"); ticket.resume(); updateResolutionDeadline(ticket,actor,"Prazo recalculado após a pausa"); audit(ticket,actor,"TICKET_RESUMED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"TICKET_RESUMED",ticket.getNumber()+" foi retomado."); return item(ticket); }
  public TicketDtos.TicketItem execute(UUID id, TicketDtos.ExecutionRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireExecutionActor(ticket,actor); if(ticket.isEvidenceRequired()&&(request.evidenceUrl()==null||request.evidenceUrl().isBlank())) throw new IllegalArgumentException("Evidência é obrigatória para este tipo de demanda"); if(request.evidenceUrl()!=null&&!request.evidenceUrl().isBlank()){try{java.net.URI uri=java.net.URI.create(request.evidenceUrl());if(uri.getScheme()==null||uri.getHost()==null||!(uri.getScheme().equalsIgnoreCase("http")||uri.getScheme().equalsIgnoreCase("https")))throw new IllegalArgumentException("Link de evidência inválido");}catch(IllegalArgumentException exception){throw new IllegalArgumentException("Link de evidência inválido");}attachments.save(new TicketAttachment(ticket,actor,"Evidência externa","", "text/uri-list",0,TicketAttachment.Kind.EVIDENCE,request.actionDescription(),request.evidenceUrl()));} TicketStatus old=ticket.getStatus(); ticket.recordExecution(ticket.isApprovalRequired()); if(ticket.getStatus()==TicketStatus.VALIDATION&&sla.pauseInValidation(ticket))ticket.pauseValidation(); if(!ticket.isApprovalRequired())audit(ticket,actor,"APPROVAL_WAIVED","typeSnapshot",null,ticket.getTypeSnapshot(),"Aprovação dispensada pela configuração aplicada ao ticket"); audit(ticket,actor,"EXECUTION_RECORDED","status",json(old),json(ticket.getStatus()),request.actionDescription()); notifications.publish(ticket,ticket.getStatus()==TicketStatus.VALIDATION?"VALIDATION_REQUESTED":"DONE",ticket.getNumber()+" teve a execução registrada."); return item(ticket); }
  public TicketDtos.TicketItem approve(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireClientOfTicket(ticket,actor); TicketStatus old=ticket.getStatus(); ticket.finishResolutionPause(Instant.now()); updateResolutionDeadline(ticket,actor,"Prazo recalculado após validação"); ticket.approve(); audit(ticket,actor,"APPROVED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"DONE",ticket.getNumber()+" foi aprovado e concluído."); return item(ticket); }
  public TicketDtos.TicketItem correct(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireClientOfTicket(ticket,actor); TicketStatus old=ticket.getStatus(); ticket.requestCorrection(); updateResolutionDeadline(ticket,actor,"Prazo recalculado após a pausa"); audit(ticket,actor,"CORRECTION_REQUESTED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"REOPENED",ticket.getNumber()+" retornou para correção."); return item(ticket); }
  public TicketDtos.TicketItem cancel(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); requireRole(actor,Role.SERVICE,Role.ADMIN); TicketStatus old=ticket.getStatus(); ticket.cancel(); audit(ticket,actor,"CANCELLED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"CANCELLED",ticket.getNumber()+" foi cancelado."); return item(ticket); }
  public TicketDtos.TicketItem reopen(UUID id, TicketDtos.ReasonRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); if(actor.getRole()==Role.CLIENT) requireClientOfTicket(ticket,actor); else requireRole(actor,Role.SERVICE,Role.ADMIN); TicketStatus old=ticket.getStatus(); try{var previous=json.createObjectNode(); previous.put("cycle",ticket.getResolutionCycle()); previous.put("priority",ticket.getPriority()==null?null:ticket.getPriority().name()); previous.put("resolutionDueAt",ticket.getResolutionDueAt()==null?null:ticket.getResolutionDueAt().toString()); previous.put("completedAt",ticket.getCompletedAt()==null?null:ticket.getCompletedAt().toString()); previous.put("slaSnapshot",ticket.getSlaRuleSnapshot()); audit(ticket,actor,"RESOLUTION_CYCLE_CLOSED","resolutionCycle",null,json.writeValueAsString(previous),request.reason());}catch(JsonProcessingException ex){throw new IllegalStateException("Falha ao preservar o ciclo de resolução");} ticket.reopenFromDone(); audit(ticket,actor,"REOPENED","status",json(old),json(ticket.getStatus()),request.reason()); notifications.publish(ticket,"REOPENED",ticket.getNumber()+" foi reaberto."); return item(ticket); }
  public TicketDtos.TicketCommentItem comment(UUID id, TicketDtos.CommentRequest request) { Ticket ticket=requiredTicket(id); AppUser actor=current.require(); if(ticket.getStatus()==TicketStatus.CANCELLED) throw new IllegalStateException("Ticket cancelado é somente consulta"); if(request.effectiveResponse()) requireRole(actor,Role.SERVICE,Role.ADMIN,Role.TRAFFIC_MANAGER); TicketComment comment=new TicketComment(ticket,actor,request.body(),request.effectiveResponse()); comments.save(comment); if(actor.getRole()==Role.CLIENT&&ticket.getStatus()==TicketStatus.WAITING_FOR_CLIENT){ticket.receiveComplement();audit(ticket,actor,"COMPLEMENT_RECEIVED",null,null,null,"Complemento recebido por comentário"); notifications.publish(ticket,"COMPLEMENT_RECEIVED",ticket.getNumber()+" recebeu complemento e aguarda conferência.");} if(request.effectiveResponse()) ticket.markEffectiveResponse(); audit(ticket,actor,"COMMENT_ADDED",null,null,null,"Comentário registrado"); notifications.publish(ticket,"COMMENT_ADDED",ticket.getNumber()+" recebeu um comentário."); return new TicketDtos.TicketCommentItem(comment.getId().toString(),actor.getName(),comment.getBody(),comment.isEffectiveResponse(),comment.getCreatedAt()); }
  private java.util.Map<String,String> fieldLabels(Ticket ticket){var labels=new java.util.LinkedHashMap<String,String>();try{for(var field:new com.fasterxml.jackson.databind.ObjectMapper().readTree(ticket.getTypeSnapshot()).path("fieldDefinitions"))labels.put(field.path("name").asText(),field.path("label").asText(field.path("name").asText()));}catch(java.io.IOException ex){throw new IllegalStateException("Configuração histórica do tipo inválida",ex);}return labels;}
  public void verifyVersion(UUID id,String expected){Ticket ticket=requiredTicket(id);if(expected==null)throw new ResponseStatusException(HttpStatus.PRECONDITION_REQUIRED,"Informe a versão do ticket (If-Match)");long value;try{value=Long.parseLong(expected.replace("\"",""));}catch(NumberFormatException ex){throw new IllegalArgumentException("Versão inválida");}if(value!=ticket.getVersionNumber())throw new org.springframework.orm.ObjectOptimisticLockingFailureException(Ticket.class,id);ticket.recordActivity();}
  public TicketDtos.TicketItem reassign(UUID id,TicketDtos.ReassignRequest request){Ticket ticket=requiredTicket(id);AppUser actor=current.require();requireRole(actor,Role.SERVICE,Role.ADMIN);AppUser assignee=users.findById(UUID.fromString(request.assigneeId())).filter(user->user.isActive()&&user.getRole()==Role.TRAFFIC_MANAGER).orElseThrow(()->new IllegalArgumentException("Responsável inválido"));String before=ticket.getAssignee()==null?null:json(ticket.getAssignee().getId());ticket.reassign(assignee);audit(ticket,actor,"ASSIGNEE_CHANGED","assigneeId",before,json(assignee.getId()),request.reason());notifications.publish(ticket,"ASSIGNED",ticket.getNumber()+" foi reatribuído.");return item(ticket);}
  private void updateResolutionDeadline(Ticket ticket,AppUser actor,String reason){Instant before=ticket.getResolutionDueAt();sla.resumeResolution(ticket);if(!Objects.equals(before,ticket.getResolutionDueAt()))audit(ticket,actor,"RESOLUTION_DEADLINE_CHANGED","resolutionDueAt",json(before),json(ticket.getResolutionDueAt()),reason);}
  private Ticket requiredTicket(UUID id) { return access.requireVisible(id,current.require()); }
  private Campaign campaign(String id, Client client) { if(id==null||id.isBlank()) return null; Campaign campaign=campaigns.findById(UUID.fromString(id)).filter(Campaign::isActive).orElseThrow(() -> new IllegalArgumentException("Campanha indisponível")); if(!campaign.getClient().getId().equals(client.getId())) throw new IllegalArgumentException("Campanha incompatível com o cliente"); return campaign; }
  private String metrics(TicketDtos.TicketMetrics metrics) { if(metrics==null)return "{}";try{return json.writeValueAsString(metrics);}catch(JsonProcessingException exception){throw new IllegalArgumentException("Métricas inválidas");} }
  private AppUser requesterFor(AppUser actor, String requesterId, Client client) { if(actor.getRole()==Role.CLIENT) return actor; if(requesterId==null||requesterId.isBlank()) throw new IllegalArgumentException("Selecione o solicitante representado"); return users.findById(UUID.fromString(requesterId)).filter(user -> user.isActive()&&user.getRole()==Role.CLIENT&&user.getClient()!=null&&user.getClient().getId().equals(client.getId())).orElseThrow(() -> new IllegalArgumentException("Solicitante inválido")); }
  private void requireRole(AppUser actor, Role... roles) { for(Role role:roles) if(actor.getRole()==role) return; throw new org.springframework.security.access.AccessDeniedException("Ação não permitida"); }
  private void requireClientOfTicket(Ticket ticket, AppUser actor) { if(actor.getRole()!=Role.CLIENT||actor.getClient()==null||!actor.getClient().getId().equals(ticket.getClient().getId())) throw new org.springframework.security.access.AccessDeniedException("Ação não permitida"); }
  private void requireExecutionActor(Ticket ticket, AppUser actor) { if(actor.getRole()!=Role.TRAFFIC_MANAGER||ticket.getAssignee()==null||!ticket.getAssignee().getId().equals(actor.getId())) throw new org.springframework.security.access.AccessDeniedException("Ação não permitida"); }
  private void audit(Ticket ticket,AppUser actor,String action,String field,String oldValue,String newValue,String reason){history.save(new TicketHistory(ticket,actor,action,field,oldValue,newValue,reason));}
  private String json(Object value){return value==null?null:"\""+value.toString()+"\"";}
  private TicketDtos.TicketItem item(Ticket ticket) { tickets.flush(); return new TicketDtos.TicketItem(ticket.getId().toString(),ticket.getClient().getId().toString(),ticket.getCampaign()==null?null:ticket.getCampaign().getId().toString(),ticket.getDemandType().getId().toString(),ticket.getNumber(),ticket.getSubject(),ticket.getClient().getName(),ticket.getCampaign()==null?null:ticket.getCampaign().getName(),ticket.getDemandType().getName(),ticket.getStatus().name(),ticket.getPriority()==null?null:ticket.getPriority().name(),ticket.getUrgency().name(),ticket.getAssignee()==null?null:ticket.getAssignee().getName(),ticket.getUpdatedAt(),actions(ticket,current.require()),ticket.getVersionNumber(),SlaService.state(ticket,Instant.now()),ticket.getStatus()!=TicketStatus.CANCELLED&&overdue(ticket,Instant.now())); }
  private List<String> actions(Ticket ticket, AppUser actor) { List<String> actions=new ArrayList<>(); TicketStatus status=ticket.getStatus(); boolean staff=actor.getRole()==Role.SERVICE||actor.getRole()==Role.ADMIN; if(staff&&status!=TicketStatus.OPEN&&status!=TicketStatus.DONE&&status!=TicketStatus.CANCELLED)actions.add("REASSIGN"); boolean assigned=actor.getRole()==Role.TRAFFIC_MANAGER&&ticket.getAssignee()!=null&&ticket.getAssignee().getId().equals(actor.getId()); if(staff&&(status==TicketStatus.OPEN||status==TicketStatus.REOPENED))actions.add("START_TRIAGE"); if(staff&&(status==TicketStatus.TRIAGE||status==TicketStatus.REOPENED))actions.add("TRIAGE"); if((staff&&status==TicketStatus.TRIAGE)||(assigned&&status==TicketStatus.EXECUTION))actions.add("WAIT"); if(assigned&&(status==TicketStatus.EXECUTION||(status==TicketStatus.REOPENED&&ticket.getSlaRuleSnapshot()!=null)))actions.add("EXECUTE"); if(actor.getRole()==Role.CLIENT&&actor.getClient()!=null&&actor.getClient().getId().equals(ticket.getClient().getId())&&status==TicketStatus.VALIDATION){actions.add("APPROVE");actions.add("REQUEST_CORRECTION");} if(status==TicketStatus.WAITING_FOR_CLIENT){if(actor.getRole()==Role.CLIENT&&actor.getClient()!=null&&actor.getClient().getId().equals(ticket.getClient().getId()))actions.add("SEND_COMPLEMENT");if(staff)actions.add("RESUME");} if(staff&&!ticket.isExecutionStarted()&&(status==TicketStatus.OPEN||status==TicketStatus.TRIAGE||(status==TicketStatus.WAITING_FOR_CLIENT&&ticket.getWaitOrigin()==WaitOrigin.TRIAGE)))actions.add("CANCEL"); if(status==TicketStatus.DONE&&(actor.getRole()==Role.CLIENT||staff))actions.add("REOPEN"); if(status!=TicketStatus.CANCELLED)actions.add("COMMENT"); return actions; }
}
