import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, Navigate, Outlet, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, AppBar, Box, Button, Card, CardContent, Chip, CircularProgress, CssBaseline, Dialog, DialogActions, DialogContent, DialogTitle, Drawer, FormControl, FormHelperText, InputLabel, List, ListItemButton, ListItemText, MenuItem, Select, Stack, TextField, ThemeProvider, Toolbar, Typography, createTheme, useMediaQuery } from '@mui/material';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { isAxiosError } from 'axios';
import { apiClient } from '../shared/api/client';
import type { Priority, Role, TicketDetail, TicketFilters, TicketItem, TicketStatus } from '../shared/api/types';
import { TicketFilterPanel } from '../shared/components/TicketFilterPanel';

const theme=createTheme({ palette:{primary:{main:'#0b5d84',dark:'#063b5a'},secondary:{main:'#0b826d'},background:{default:'#f5f7fa'}},shape:{borderRadius:10},typography:{fontFamily:'Inter, system-ui, sans-serif'} });
const statuses:TicketStatus[]=['OPEN','TRIAGE','EXECUTION','WAITING_FOR_CLIENT','VALIDATION','DONE','REOPENED','CANCELLED'];
const priorities:Priority[]=['URGENT','HIGH','MEDIUM','LOW'];
const metricValue=z.string().trim().refine(value=>!value||(Number.isFinite(Number(value.replace(',','.')))&&Number(value.replace(',','.'))>=0));
const newTicketSchema=z.object({clientId:z.string().min(1),requesterId:z.string(),campaignId:z.string(),pendingCampaign:z.string().trim(),demandTypeId:z.string().min(1),channel:z.string().trim().min(1).max(80),subject:z.string().trim().min(1).max(255),description:z.string().trim().min(1),urgency:z.enum(['URGENT','HIGH','MEDIUM','LOW']),desiredDate:z.string(),metricPeriod:z.string().trim().max(120),impressions:metricValue,ctr:metricValue,cpc:metricValue,conversions:metricValue,cpa:metricValue,roas:metricValue}).superRefine((value,context)=>{if(!value.campaignId&&!value.pendingCampaign)context.addIssue({code:'custom',path:['pendingCampaign']});});
type NewTicketForm=z.infer<typeof newTicketSchema>;
type DynamicField={name:string;label:string;required:boolean};
function dynamicFields(source:string|undefined):DynamicField[]{try{const parsed=JSON.parse(source??'[]');if(!Array.isArray(parsed))return [];return parsed.flatMap(item=>typeof item==='object'&&item!==null&&typeof item.name==='string'&&item.name.trim()?[{name:item.name.trim(),label:typeof item.label==='string'&&item.label.trim()?item.label.trim():item.name.trim(),required:item.required===true}]:[]);}catch{return [];}}
const metricNumber=(value:string)=>value.trim()?Number(value.replace(',','.')):null;
const metrics=(form:NewTicketForm,fields:Record<string,string>)=>({period:form.metricPeriod||null,impressions:metricNumber(form.impressions),ctr:metricNumber(form.ctr),cpc:metricNumber(form.cpc),conversions:metricNumber(form.conversions),cpa:metricNumber(form.cpa),roas:metricNumber(form.roas),fields});
const navByRole:Record<Role,string[]>={CLIENT:['dashboard','tickets','notifications'],SERVICE:['dashboard','tickets','notifications','reports','campaigns'],TRAFFIC_MANAGER:['dashboard','tickets','notifications'],ADMIN:['dashboard','tickets','notifications','reports','clients','campaigns','demandTypes','sla','users']};
const navigation:{key:string;path:string}[]=[{key:'dashboard',path:'/'},{key:'tickets',path:'/tickets'},{key:'notifications',path:'/notifications'},{key:'reports',path:'/reports'},{key:'clients',path:'/clients'},{key:'campaigns',path:'/campaigns'},{key:'demandTypes',path:'/demand-types'},{key:'sla',path:'/sla'},{key:'users',path:'/users'}];
const tutorialSteps:Record<Role,number>={CLIENT:4,SERVICE:4,TRAFFIC_MANAGER:4,ADMIN:5};

function Loading(){const {t}=useTranslation();return <Stack alignItems="center" spacing={2} sx={{py:8}}><CircularProgress/><Typography>{t('messages.loading')}</Typography></Stack>}
type ApiErrorPayload={code?:string};
function Failure({error}:{error?:unknown}){const {t}=useTranslation();const code=isAxiosError<ApiErrorPayload>(error)?error.response?.data?.code:undefined;const key=code==='FORBIDDEN'?'messages.forbidden':code==='VALIDATION_ERROR'?'messages.validation':code==='BUSINESS_RULE'?'messages.business':code==='INVALID_TRANSITION'||code==='VERSION_CONFLICT'?'messages.conflict':'messages.error';return <Alert severity="error">{t(key)}</Alert>}
function date(value:string|null){return value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'}
function StatusChip({status}:{status:TicketStatus}){const {t}=useTranslation();return <Chip size="small" label={t(`status.${status}`)} color={status==='DONE'?'success':status==='CANCELLED'?'default':status==='WAITING_FOR_CLIENT'?'warning':'primary'} variant="outlined"/>}

function Login(){const {t}=useTranslation();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const mutation=useMutation({mutationFn:()=>apiClient.login(email,password),onSuccess:()=>navigate('/',{replace:true})});return <Box sx={{minHeight:'100vh',display:'grid',gridTemplateColumns:{md:'1fr 480px'},bgcolor:'background.default'}}><Box sx={{display:{xs:'none',md:'flex'},p:8,color:'white',flexDirection:'column',justifyContent:'space-between',background:'linear-gradient(145deg,#063b5a,#0b826d)'}}><Box><Typography variant="h4" fontWeight={800}>{t('app.name')}</Typography><Typography variant="h3" sx={{mt:10,maxWidth:500}}>{t('app.tagline')}</Typography></Box></Box><Stack component="form" onSubmit={event=>{event.preventDefault();mutation.mutate();}} justifyContent="center" spacing={3} sx={{p:{xs:3,sm:6}}}><Box><Typography variant="h4" fontWeight={700}>{t('login.title')}</Typography><Typography color="text.secondary" sx={{mt:1}}>{t('login.subtitle')}</Typography></Box>{mutation.isError&&<Alert severity="error">{t('login.invalid')}</Alert>}<TextField label={t('login.email')} type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="email"/><TextField label={t('login.password')} type="password" value={password} onChange={event=>setPassword(event.target.value)} required autoComplete="current-password"/><Button type="submit" size="large" variant="contained" disabled={mutation.isPending}>{t('actions.login')}</Button></Stack></Box>}

function TutorialDialog({role,onClose}:{role:Role;onClose:()=>void}){const {t}=useTranslation();const [step,setStep]=useState(0);const total=tutorialSteps[role];return <Dialog open onClose={onClose} fullWidth maxWidth="sm" aria-labelledby="tutorial-title"><DialogTitle id="tutorial-title">{t('tutorial.title')}</DialogTitle><DialogContent><Typography color="text.secondary">{t('tutorial.progress',{current:step+1,total})}</Typography><Typography variant="h6" sx={{mt:2}}>{t(`tutorial.steps.${role}.${step}.title`)}</Typography><Typography sx={{mt:1}}>{t(`tutorial.steps.${role}.${step}.text`)}</Typography></DialogContent><DialogActions><Button onClick={onClose}>{t('tutorial.close')}</Button><Button onClick={()=>setStep(current=>Math.max(0,current-1))} disabled={step===0}>{t('tutorial.previous')}</Button><Button variant="contained" onClick={()=>step===total-1?onClose():setStep(current=>current+1)}>{step===total-1?t('tutorial.finish'):t('tutorial.next')}</Button></DialogActions></Dialog>}
function Layout(){const {t}=useTranslation();const session=useQuery({queryKey:['session'],queryFn:apiClient.me});const navigate=useNavigate();const cache=useQueryClient();const compact=useMediaQuery(theme.breakpoints.down('md'));const [menuOpen,setMenuOpen]=useState(false);const [tutorialOpen,setTutorialOpen]=useState(false);if(session.isPending)return <Loading/>;if(session.isError)return <Navigate to="/login" replace/>;const user=session.data;const logout=async()=>{await apiClient.logout();cache.removeQueries();navigate('/login',{replace:true});};const items=navigation.filter(item=>navByRole[user.role].includes(item.key));return <Box sx={{display:'flex',minHeight:'100vh'}}><CssBaseline/><AppBar position="fixed" color="inherit" elevation={0} sx={{borderBottom:1,borderColor:'divider',zIndex:1201}}><Toolbar sx={{justifyContent:'space-between'}}><Stack direction="row" spacing={1} alignItems="center">{compact&&<Button onClick={()=>setMenuOpen(true)}>{t('actions.menu')}</Button>}<Typography color="primary" fontWeight={800}>{t('app.name')}</Typography></Stack><Stack direction="row" spacing={2} alignItems="center"><Typography sx={{display:{xs:'none',sm:'block'}}} variant="body2" color="text.secondary">{user.name} · {t(`role.${user.role}`)}</Typography><Button onClick={logout}>{t('actions.logout')}</Button></Stack></Toolbar></AppBar><Drawer variant={compact?'temporary':'permanent'} open={compact?menuOpen:true} onClose={()=>setMenuOpen(false)} sx={{width:250,flexShrink:0,'& .MuiDrawer-paper':{width:250,boxSizing:'border-box',pt:8}}}><List>{items.map(item=><ListItemButton key={item.key} component={Link} to={item.path} onClick={()=>setMenuOpen(false)}><ListItemText primary={t(`nav.${item.key}`)}/></ListItemButton>)}</List><Box sx={{mt:'auto',p:2}}><Button fullWidth variant="outlined" onClick={()=>{setMenuOpen(false);setTutorialOpen(true);}}>{t('tutorial.open')}</Button></Box></Drawer><Box component="main" sx={{flexGrow:1,p:{xs:2,md:4},pt:{xs:10,md:12},maxWidth:1600,width:'100%',mx:'auto'}}><Outlet/></Box>{tutorialOpen&&<TutorialDialog role={user.role} onClose={()=>setTutorialOpen(false)}/>}</Box>}

function DashboardPage(){const {t}=useTranslation();const dashboard=useQuery({queryKey:['dashboard'],queryFn:apiClient.dashboard});if(dashboard.isPending)return <Loading/>;if(dashboard.isError)return <Failure error={dashboard.error}/>;const data=dashboard.data;const metrics=[['active',data.activeCount],['priority',data.highPriorityCount],['validation',data.validationCount],['waiting',data.waitingCount],['overdue',data.overdueCount]];return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={700}>{t('dashboard.title')}</Typography></Box><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:2}}>{metrics.map(([key,value])=><Card key={key}><CardContent><Typography color="text.secondary">{t(`dashboard.${key}`)}</Typography><Typography variant="h3" fontWeight={700}>{value}</Typography></CardContent></Card>)}</Box><Box sx={{display:'grid',gridTemplateColumns:{lg:'1fr 1fr'},gap:3}}><Card><CardContent><Typography variant="h6">{t('dashboard.distribution')}</Typography><Stack direction="row" flexWrap="wrap" gap={1} mt={2}>{data.statusDistribution.map(item=><Chip key={item.status} label={`${t(`status.${item.status}`)} · ${item.count}`}/>)}</Stack></CardContent></Card><Card><CardContent><Typography variant="h6">{t('dashboard.slaHealth')}</Typography><Typography color="text.secondary" variant="body2">{t('dashboard.classified',{count:data.classifiedCount})}</Typography><Typography variant="h4" color={data.overdueCount?'error.main':'success.main'} sx={{mt:2}}>{data.overdueCount}</Typography><Typography variant="body2">{t('dashboard.overdue')}</Typography></CardContent></Card><Card><CardContent><Typography variant="h6">{t('dashboard.recent')}</Typography><Stack spacing={1} mt={2}>{data.recent.map(item=><Button key={item.id} component={Link} to={`/tickets/${item.id}`} sx={{justifyContent:'space-between'}}>{item.number} · {item.subject}<StatusChip status={item.status}/></Button>)}</Stack></CardContent></Card></Box></Stack>}

function TicketsPage(){
  const {t}=useTranslation(); const [filters,setFilters]=useState<TicketFilters>({}); const [page,setPage]=useState(0); const [view,setView]=useState<'kanban'|'table'>('kanban'); const refs=useQuery({queryKey:['reference'],queryFn:apiClient.reference}); const session=useQuery({queryKey:['session'],queryFn:apiClient.me}); const query=useQuery({queryKey:['tickets',filters,page],queryFn:()=>apiClient.tickets({...filters,page,size:25})});
  if(query.isPending||refs.isPending||session.isPending)return <Loading/>; if(query.isError||refs.isError||session.isError)return <Failure error={query.error??refs.error??session.error}/>;
  const pages=Math.max(1,Math.ceil(query.data.total/query.data.size));
  const canCreate=session.data.role!=='TRAFFIC_MANAGER';
  return <Stack spacing={3}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={700}>{t('tickets.title')}</Typography><Typography color="text.secondary">{t('tickets.subtitle')}</Typography></Box>{canCreate&&<Button component={Link} to="/tickets/new" variant="contained">{t('actions.create')}</Button>}</Stack><Card><CardContent><TicketFilterPanel filters={filters} onChange={next=>{setFilters(next);setPage(0);}} reference={refs.data} searchPlaceholder={t('tickets.searchPlaceholder')}/><Stack direction="row" justifyContent="flex-end"><Stack direction="row" spacing={1}><Button variant={view==='kanban'?'contained':'outlined'} onClick={()=>setView('kanban')}>{t('actions.kanban')}</Button><Button variant={view==='table'?'contained':'outlined'} onClick={()=>setView('table')}>{t('actions.table')}</Button></Stack></Stack></CardContent></Card>{view==='kanban'?<TicketKanban items={query.data.items}/>:<TicketTable items={query.data.items}/>}<Stack direction="row" spacing={2} justifyContent="flex-end" alignItems="center"><Typography variant="body2" color="text.secondary">{t('tickets.page',{current:page+1,total:pages})}</Typography><Button onClick={()=>setPage(current=>current-1)} disabled={page===0}>{t('tutorial.previous')}</Button><Button onClick={()=>setPage(current=>current+1)} disabled={page+1>=pages}>{t('tutorial.next')}</Button></Stack></Stack>
}
function TicketTable({items}:{items:TicketItem[]}){const {t}=useTranslation();if(!items.length)return <Alert severity="info">{t('tickets.noItems')}</Alert>;return <Stack spacing={1}>{items.map(item=><Card key={item.id} component={Link} to={`/tickets/${item.id}`} sx={{textDecoration:'none',color:'inherit'}}><CardContent sx={{display:'grid',gridTemplateColumns:{md:'1.5fr 1fr 1fr 1fr'},gap:2,alignItems:'center'}}><Box><Typography fontWeight={700}>{item.number} · {item.subject}</Typography><Typography variant="body2" color="text.secondary">{item.typeName}</Typography></Box><Typography>{item.clientName}</Typography><StatusChip status={item.status}/><Typography variant="body2" color="text.secondary">{date(item.updatedAt)}</Typography></CardContent></Card>)}</Stack>}
function TicketKanban({items}:{items:TicketItem[]}){const {t}=useTranslation();if(!items.length)return <Alert severity="info">{t('tickets.noItems')}</Alert>;return <Box sx={{display:'grid',gridTemplateColumns:'repeat(8,minmax(230px,1fr))',gap:2,overflowX:'auto',pb:2}}>{statuses.map(status=><Stack key={status} spacing={1} sx={{minWidth:230}}><Stack direction="row" justifyContent="space-between" alignItems="center"><StatusChip status={status}/><Chip size="small" label={items.filter(item=>item.status===status).length}/></Stack>{items.filter(item=>item.status===status).map(item=><Card key={item.id} component={Link} to={`/tickets/${item.id}`} sx={{textDecoration:'none',color:'inherit'}}><CardContent><Typography fontWeight={700} variant="body2">{item.number}</Typography><Typography variant="body2">{item.subject}</Typography><Typography variant="caption" display="block" color="text.secondary" sx={{mt:1}}>{item.clientName}</Typography>{item.priority&&<Chip size="small" sx={{mt:1}} label={t(`priority.${item.priority}`)}/>}</CardContent></Card>)}</Stack>)}</Box>}

function NewTicketPage(){
  const {t}=useTranslation(); const navigate=useNavigate(); const refs=useQuery({queryKey:['reference'],queryFn:apiClient.reference}); const session=useQuery({queryKey:['session'],queryFn:apiClient.me}); const [files,setFiles]=useState<File[]>([]); const [customFields,setCustomFields]=useState<Record<string,string>>({}); const [customErrors,setCustomErrors]=useState<Record<string,boolean>>({}); const {control,register,handleSubmit,setError,setValue,watch,formState:{errors}}=useForm<NewTicketForm>({resolver:zodResolver(newTicketSchema),defaultValues:{clientId:'',requesterId:'',campaignId:'',pendingCampaign:'',demandTypeId:'',channel:'',subject:'',description:'',urgency:'MEDIUM',desiredDate:'',metricPeriod:'',impressions:'',ctr:'',cpc:'',conversions:'',cpa:'',roas:''}});
  useEffect(()=>{if(session.data?.role==='CLIENT'&&session.data.clientId)setValue('clientId',session.data.clientId);},[session.data?.clientId,session.data?.role,setValue]);
  const create=useMutation({mutationFn:async(form:NewTicketForm)=>{const ticket=await apiClient.createTicket({...form,desiredDate:form.desiredDate||null,campaignId:form.campaignId||null,pendingCampaign:form.pendingCampaign||null,requesterId:form.requesterId||null,metrics:metrics(form,customFields)});await Promise.all(files.map(file=>apiClient.uploadAttachment(ticket.id,file)));return ticket;},onSuccess:ticket=>navigate(`/tickets/${ticket.id}`)});
  if(refs.isPending||session.isPending)return <Loading/>; if(refs.isError||session.isError)return <Failure error={refs.error??session.error}/>;
  if(session.data.role==='TRAFFIC_MANAGER')return <Navigate to="/tickets" replace/>;
  const isClient=session.data.role==='CLIENT'; const clients=isClient?[{id:session.data.clientId!,label:refs.data.clients.find(item=>item.id===session.data.clientId)?.label??''}]:refs.data.clients;
  const clientId=watch('clientId'); const demandTypeId=watch('demandTypeId'); const campaigns=refs.data.campaigns.filter(item=>item.clientId===clientId); const requesters=refs.data.clientUsers.filter(item=>item.clientId===clientId); const configuredFields=dynamicFields(refs.data.demandTypes.find(item=>item.id===demandTypeId)?.fieldDefinitions);
  const submit=(form:NewTicketForm)=>{if(!isClient&&!form.requesterId){setError('requesterId',{type:'required'});return;}const invalid=Object.fromEntries(configuredFields.filter(field=>field.required&&!customFields[field.name]?.trim()).map(field=>[field.name,true]));if(Object.keys(invalid).length){setCustomErrors(invalid);return;}create.mutate(form);};
  const selectError=(name:keyof NewTicketForm)=>errors[name]?<FormHelperText>{t('messages.required')}</FormHelperText>:null;
  return <Stack spacing={3}><Typography variant="h4" fontWeight={700}>{t('tickets.newTitle')}</Typography>{create.isError&&<Failure error={create.error}/>}<Card component="form" onSubmit={handleSubmit(submit)}><CardContent><Stack spacing={2}>
    <Controller name="clientId" control={control} render={({field})=><FormControl required error={Boolean(errors.clientId)}><InputLabel>{t('tickets.client')}</InputLabel><Select {...field} label={t('tickets.client')} onChange={event=>{field.onChange(event);setValue('requesterId','');setValue('campaignId','');}}>{clients.map(item=><MenuItem key={item.id} value={item.id}>{item.label}</MenuItem>)}</Select>{selectError('clientId')}</FormControl>}/>
    {!isClient&&<Controller name="requesterId" control={control} render={({field})=><FormControl required error={Boolean(errors.requesterId)}><InputLabel>{t('tickets.requester')}</InputLabel><Select {...field} label={t('tickets.requester')}>{requesters.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select>{selectError('requesterId')}</FormControl>}/>} 
    <Controller name="campaignId" control={control} render={({field})=><FormControl><InputLabel>{t('tickets.campaign')}</InputLabel><Select {...field} label={t('tickets.campaign')}><MenuItem value="">{t('actions.all')}</MenuItem>{campaigns.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></FormControl>}/><TextField label={t('tickets.pendingCampaign')} error={Boolean(errors.pendingCampaign)} helperText={errors.pendingCampaign&&t('messages.required')} {...register('pendingCampaign')}/>
    <Controller name="demandTypeId" control={control} render={({field})=><FormControl required error={Boolean(errors.demandTypeId)}><InputLabel>{t('tickets.type')}</InputLabel><Select {...field} label={t('tickets.type')} onChange={event=>{field.onChange(event);setCustomFields({});setCustomErrors({});}}>{refs.data.demandTypes.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select>{selectError('demandTypeId')}</FormControl>}/><TextField required label={t('tickets.channel')} error={Boolean(errors.channel)} helperText={errors.channel&&t('messages.required')} {...register('channel')}/><TextField required label={t('tickets.subject')} error={Boolean(errors.subject)} helperText={errors.subject&&t('messages.required')} {...register('subject')}/><TextField required multiline minRows={4} label={t('tickets.description')} error={Boolean(errors.description)} helperText={errors.description&&t('messages.required')} {...register('description')}/>
    {configuredFields.length>0&&<><Typography variant="h6" sx={{pt:1}}>{t('tickets.additionalFields')}</Typography><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:2}}>{configuredFields.map(field=><TextField key={field.name} required={field.required} label={field.label} value={customFields[field.name]??''} error={Boolean(customErrors[field.name])} helperText={customErrors[field.name]&&t('messages.required')} onChange={event=>{setCustomFields(values=>({...values,[field.name]:event.target.value}));setCustomErrors(errors=>({...errors,[field.name]:false}));}}/>)}</Box></>}
    <Controller name="urgency" control={control} render={({field})=><FormControl><InputLabel>{t('tickets.urgency')}</InputLabel><Select {...field} label={t('tickets.urgency')}>{priorities.map(item=><MenuItem key={item} value={item}>{t(`priority.${item}`)}</MenuItem>)}</Select></FormControl>}/><TextField type="date" label={t('tickets.desiredDate')} InputLabelProps={{shrink:true}} {...register('desiredDate')}/>
    <Typography variant="h6" sx={{pt:1}}>{t('tickets.metrics')}</Typography><Typography variant="body2" color="text.secondary">{t('tickets.metricsHint')}</Typography><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:2}}><TextField label={t('metrics.period')} {...register('metricPeriod')}/><TextField label={t('metrics.impressions')} inputMode="numeric" error={Boolean(errors.impressions)} helperText={errors.impressions&&t('messages.nonNegative')} {...register('impressions')}/><TextField label={t('metrics.ctr')} inputMode="decimal" error={Boolean(errors.ctr)} helperText={errors.ctr&&t('messages.nonNegative')} {...register('ctr')}/><TextField label={t('metrics.cpc')} inputMode="decimal" error={Boolean(errors.cpc)} helperText={errors.cpc&&t('messages.nonNegative')} {...register('cpc')}/><TextField label={t('metrics.conversions')} inputMode="numeric" error={Boolean(errors.conversions)} helperText={errors.conversions&&t('messages.nonNegative')} {...register('conversions')}/><TextField label={t('metrics.cpa')} inputMode="decimal" error={Boolean(errors.cpa)} helperText={errors.cpa&&t('messages.nonNegative')} {...register('cpa')}/><TextField label={t('metrics.roas')} inputMode="decimal" error={Boolean(errors.roas)} helperText={errors.roas&&t('messages.nonNegative')} {...register('roas')}/></Box>
    <Typography variant="h6" sx={{pt:1}}>{t('tickets.attachments')}</Typography><Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap><Button component="label" variant="outlined">{t('actions.attach')}<input hidden type="file" multiple accept="image/*,.pdf,.csv,.xlsx" onChange={event=>setFiles(Array.from(event.target.files??[]))}/></Button>{files.map(file=><Chip key={`${file.name}-${file.size}`} label={file.name} onDelete={()=>setFiles(current=>current.filter(item=>item!==file))}/>)}</Stack>
    <Stack direction="row" justifyContent="flex-end" gap={2}><Button component={Link} to="/tickets">{t('actions.cancel')}</Button><Button type="submit" variant="contained" disabled={create.isPending}>{t('actions.create')}</Button></Stack>
  </Stack></CardContent></Card></Stack>
}

const actionLabels:Record<string,string>={START_TRIAGE:'actions.startTriage',TRIAGE:'actions.triage',WAIT:'actions.wait',EXECUTE:'actions.execute',APPROVE:'actions.approve',REQUEST_CORRECTION:'actions.correction',SEND_COMPLEMENT:'actions.send',RESUME:'actions.resume',CANCEL:'actions.cancel',REOPEN:'actions.reopen',COMMENT:'tickets.comments'};
function ActionDialog({ticket,action,onClose}:{ticket:TicketDetail;action:string;onClose:()=>void}){
  const {t}=useTranslation(); const cache=useQueryClient(); const [reason,setReason]=useState(''); const [priority,setPriority]=useState<Priority>('MEDIUM'); const [assigneeId,setAssigneeId]=useState(''); const [campaignId,setCampaignId]=useState(ticket.ticket.campaignId??''); const [demandTypeId,setDemandTypeId]=useState(ticket.ticket.demandTypeId); const [effectiveResponse,setEffectiveResponse]=useState(''); const [evidenceUrl,setEvidenceUrl]=useState('');
  const refs=useQuery({queryKey:['reference'],queryFn:apiClient.reference,enabled:action==='TRIAGE'});
  const mutation=useMutation({
    mutationFn:async()=>{
      const id=ticket.ticket.id;
      if(action==='START_TRIAGE') return apiClient.action(id,'triage/start',{reason});
      if(action==='TRIAGE') return apiClient.action(id,'triage',{priority,assigneeId,campaignId,demandTypeId,effectiveResponse,sendToExecution:true});
      if(action==='WAIT') return apiClient.action(id,'wait',{reason});
      if(action==='EXECUTE') return apiClient.action(id,'execution',{actionDescription:reason,evidenceUrl});
      if(action==='APPROVE') return apiClient.action(id,'approve',{reason});
      if(action==='REQUEST_CORRECTION') return apiClient.action(id,'correction',{reason});
      if(action==='SEND_COMPLEMENT') return apiClient.action(id,'complement',{body:reason,effectiveResponse:false});
      if(action==='RESUME') return apiClient.action(id,'resume',{reason});
      if(action==='CANCEL') return apiClient.action(id,'cancel',{reason});
      if(action==='REOPEN') return apiClient.action(id,'reopen',{reason});
      return apiClient.comment(id,{body:reason,effectiveResponse:effectiveResponse==='true'});
    },
    onSuccess:()=>{ cache.invalidateQueries({queryKey:['ticket',ticket.ticket.id]}); cache.invalidateQueries({queryKey:['tickets']}); cache.invalidateQueries({queryKey:['dashboard']}); cache.invalidateQueries({queryKey:['notifications']}); onClose(); }
  });
  const needText=action!=='TRIAGE';
  return <Dialog open onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{t(actionLabels[action])}</DialogTitle><DialogContent><Stack sx={{pt:1}} spacing={2}><Box sx={{p:1.5,border:1,borderColor:'divider',borderRadius:1}}><Typography fontWeight={700}>{ticket.ticket.number} · {ticket.ticket.subject}</Typography><Typography variant="body2" color="text.secondary">{ticket.ticket.clientName} · {ticket.ticket.typeName}</Typography></Box>
    {action==='TRIAGE'&&<>{refs.isPending?<Loading/>:refs.isError?<Failure error={refs.error}/>:<><FormControl required><InputLabel>{t('tickets.campaign')}</InputLabel><Select label={t('tickets.campaign')} value={campaignId} onChange={event=>setCampaignId(event.target.value)}>{refs.data.campaigns.filter(item=>item.clientId===ticket.ticket.clientId).map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></FormControl><FormControl required><InputLabel>{t('tickets.type')}</InputLabel><Select label={t('tickets.type')} value={demandTypeId} onChange={event=>setDemandTypeId(event.target.value)}>{refs.data.demandTypes.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>{t('tickets.priority')}</InputLabel><Select label={t('tickets.priority')} value={priority} onChange={event=>setPriority(event.target.value as Priority)}>{priorities.map(item=><MenuItem key={item} value={item}>{t(`priority.${item}`)}</MenuItem>)}</Select></FormControl><FormControl required><InputLabel>{t('tickets.assignee')}</InputLabel><Select label={t('tickets.assignee')} value={assigneeId} onChange={event=>setAssigneeId(event.target.value)}>{refs.data.trafficManagers.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></FormControl><TextField required label={t('tickets.comments')} value={effectiveResponse} onChange={event=>setEffectiveResponse(event.target.value)}/></>}</>}
    {needText&&<TextField required multiline minRows={3} label={action==='EXECUTE'?t('tickets.actionDescription'):action==='SEND_COMPLEMENT'?t('tickets.complement'):action==='WAIT'?t('tickets.waitReason'):t('tickets.reason')} value={reason} onChange={event=>setReason(event.target.value)}/>} {action==='EXECUTE'&&<TextField label={t('tickets.evidenceUrl')} value={evidenceUrl} onChange={event=>setEvidenceUrl(event.target.value)}/>} {action==='COMMENT'&&<FormControl><InputLabel>{t('tickets.effectiveResponse')}</InputLabel><Select label={t('tickets.effectiveResponse')} value={effectiveResponse} onChange={event=>setEffectiveResponse(event.target.value)}><MenuItem value="false">{t('actions.no')}</MenuItem><MenuItem value="true">{t('actions.yes')}</MenuItem></Select></FormControl>} {mutation.isError&&<Failure error={mutation.error}/>}
  </Stack></DialogContent><DialogActions><Button onClick={onClose}>{t('actions.cancel')}</Button><Button variant="contained" onClick={()=>mutation.mutate()} disabled={mutation.isPending||(action==='TRIAGE'&&(!assigneeId||!campaignId||!demandTypeId||!effectiveResponse))||(needText&&!reason)}>{t('actions.save')}</Button></DialogActions></Dialog>
}

function AttachmentUploader({ticketId}:{ticketId:string}){
  const {t}=useTranslation(); const cache=useQueryClient(); const [file,setFile]=useState<File|null>(null);
  const upload=useMutation({mutationFn:()=>apiClient.uploadAttachment(ticketId,file!),onSuccess:()=>{setFile(null);cache.invalidateQueries({queryKey:['ticket',ticketId]});}});
  return <Stack direction={{xs:'column',sm:'row'}} spacing={1} sx={{mt:2}}><Button component="label" variant="outlined">{t('actions.attach')}<input hidden type="file" accept="image/*,.pdf,.csv,.xlsx" onChange={event=>setFile(event.target.files?.[0]??null)}/></Button>{file&&<Button onClick={()=>upload.mutate()} disabled={upload.isPending} variant="contained">{t('actions.send')}</Button>}{upload.isError&&<Alert severity="error">{t('messages.error')}</Alert>}</Stack>
}
function TicketMetricsCard({source}:{source:string|null}){const {t}=useTranslation();let values:Record<string,unknown>={};try{values=source?JSON.parse(source) as Record<string,unknown>:{}}catch{values={};}const filled:[string,unknown][]=Object.entries(values).flatMap(([key,value]):[string,unknown][]=>key==='fields'&&typeof value==='object'&&value!==null?Object.entries(value as Record<string,unknown>):[[key,value]]).filter(([,value])=>value!==null&&value!=='');if(!filled.length)return null;return <Card><CardContent><Typography variant="h6">{t('tickets.metrics')}</Typography><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:2,mt:2}}>{filled.map(([key,value])=><Box key={key}><Typography variant="caption" color="text.secondary">{t(`metrics.${key}`,{defaultValue:key})}</Typography><Typography>{String(value)}</Typography></Box>)}</Box></CardContent></Card>}

function TicketDetailPage(){
  const {t}=useTranslation(); const params=useParams(); const query=useQuery({queryKey:['ticket',params.id],queryFn:()=>apiClient.ticket(params.id!)}); const [action,setAction]=useState<string|null>(null);
  if(query.isPending)return <Loading/>; if(query.isError)return <Failure error={query.error}/>; const data=query.data;
  return <Stack spacing={3}>
    <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={700}>{data.ticket.number} · {data.ticket.subject}</Typography><Typography color="text.secondary">{data.ticket.clientName} · {data.requesterName}</Typography></Box><StatusChip status={data.ticket.status}/></Stack>
    <Stack direction="row" flexWrap="wrap" gap={1}>{data.ticket.actions.map(item=><Button key={item} variant={item==='APPROVE'?'contained':'outlined'} onClick={()=>setAction(item)}>{t(actionLabels[item])}</Button>)}</Stack>
    <Box sx={{display:'grid',gridTemplateColumns:{lg:'1.6fr 1fr'},gap:3}}><Stack spacing={3}>
      <Card><CardContent><Typography variant="h6">{t('tickets.description')}</Typography><Typography sx={{whiteSpace:'pre-wrap',mt:1}}>{data.description}</Typography></CardContent></Card><TicketMetricsCard source={data.metrics}/>
      <Card><CardContent><Typography variant="h6">{t('tickets.attachments')}</Typography><Stack spacing={1} mt={2}>{data.attachments.length===0?<Typography color="text.secondary">—</Typography>:data.attachments.map(item=><Box key={item.id}><Typography fontWeight={600}>{item.description??item.name}</Typography>{item.evidenceUrl?<Button component="a" href={item.evidenceUrl} target="_blank" rel="noreferrer">{item.evidenceUrl}</Button>:<Button component="a" href={apiClient.attachmentDownloadUrl(data.ticket.id,item.id)}>{t('actions.download')}</Button>}<Typography variant="caption" display="block" color="text.secondary">{date(item.createdAt)}</Typography></Box>)}</Stack>{data.ticket.status!=='CANCELLED'&&<AttachmentUploader ticketId={data.ticket.id}/>}</CardContent></Card>
      <Card><CardContent><Typography variant="h6">{t('tickets.comments')}</Typography><Stack spacing={2} mt={2}>{data.comments.map(item=><Box key={item.id}><Typography fontWeight={600}>{item.authorName}</Typography><Typography>{item.body}</Typography><Typography variant="caption" color="text.secondary">{date(item.createdAt)}</Typography></Box>)}</Stack></CardContent></Card>
    </Stack><Stack spacing={3}><Card><CardContent><Typography variant="h6">{t('tickets.sla')}</Typography><Typography>{data.slaState}</Typography><Typography variant="body2">{date(data.responseDueAt)} · {date(data.resolutionDueAt)}</Typography></CardContent></Card><Card><CardContent><Typography variant="h6">{t('tickets.history')}</Typography><Stack spacing={2} mt={2}>{data.history.map(item=><Box key={item.id}><Typography fontWeight={600}>{item.action}</Typography><Typography variant="body2">{item.actorName} · {date(item.createdAt)}</Typography><Typography variant="body2" color="text.secondary">{item.reason}</Typography></Box>)}</Stack></CardContent></Card></Stack></Box>
    {action&&<ActionDialog ticket={data} action={action} onClose={()=>setAction(null)}/>}</Stack>
}

function NotificationsPage(){const {t}=useTranslation();const cache=useQueryClient();const query=useQuery({queryKey:['notifications'],queryFn:apiClient.notifications});const read=useMutation({mutationFn:apiClient.readNotification,onSuccess:()=>cache.invalidateQueries({queryKey:['notifications']})});if(query.isPending)return <Loading/>;if(query.isError)return <Failure error={query.error}/>;return <Stack spacing={3}><Typography variant="h4" fontWeight={700}>{t('notifications.title')}</Typography>{query.data.items.length===0?<Alert severity="info">{t('notifications.empty')}</Alert>:query.data.items.map(item=><Card key={item.id} component={Link} to={`/tickets/${item.ticketId}`} sx={{textDecoration:'none',color:'inherit'}}><CardContent sx={{display:'flex',justifyContent:'space-between',gap:2}}><Box><Typography fontWeight={item.readAt?400:700}>{item.ticketNumber} · {item.summary}</Typography><Typography variant="body2" color="text.secondary">{date(item.createdAt)}</Typography></Box>{!item.readAt&&<Button onClick={event=>{event.preventDefault();read.mutate(item.id)}}>{t('actions.markRead')}</Button>}</CardContent></Card>)}</Stack>}
type ManagementField={key:string;type?:'text'|'email'|'password'|'time'|'checkbox'|'select'|'textarea';createOnly?:boolean;options?:string[]};
const managementFields:Record<string,ManagementField[]>={
  clients:[{key:'name'},{key:'contactName'},{key:'email',type:'email'},{key:'phone'}],
  campaigns:[{key:'clientId',type:'select'},{key:'name'},{key:'channel'},{key:'objective'}],
  'demand-types':[{key:'name'},{key:'approvalRequired',type:'checkbox'},{key:'evidenceRequired',type:'checkbox'},{key:'fieldDefinitions',type:'textarea'}],
  users:[{key:'name'},{key:'email',type:'email'},{key:'password',type:'password',createOnly:true},{key:'role',type:'select'},{key:'clientId',type:'select'},{key:'active',type:'checkbox'}],
  'sla-rules':[{key:'name'},{key:'scope',type:'select'},{key:'clientId',type:'select'},{key:'demandTypeId',type:'select'},{key:'timezone'},{key:'businessDays',type:'textarea'},{key:'businessStart',type:'time'},{key:'businessEnd',type:'time'},{key:'holidays',type:'textarea'},{key:'pauseInValidation',type:'checkbox'},{key:'deadlines',type:'textarea'},{key:'active',type:'checkbox'}],
};
const managementDefaults:Record<string,Record<string,unknown>>={
  'demand-types':{approvalRequired:false,evidenceRequired:false,fieldDefinitions:'[]'},users:{active:true,role:'CLIENT'},
  'sla-rules':{scope:'DEFAULT',timezone:'America/Sao_Paulo',businessDays:'["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY"]',businessStart:'08:00',businessEnd:'18:00',holidays:'[]',pauseInValidation:false,deadlines:'{"URGENT":{"responseHours":2,"resolutionHours":8},"HIGH":{"responseHours":4,"resolutionHours":16},"MEDIUM":{"responseHours":8,"resolutionHours":24},"LOW":{"responseHours":16,"resolutionHours":40}}',active:true},
};
function ManagementDialog({resource,item,onClose}:{resource:string;item:Record<string,unknown>|null;onClose:()=>void}){
  const {t}=useTranslation(); const cache=useQueryClient(); const refs=useQuery({queryKey:['reference'],queryFn:apiClient.reference}); const [values,setValues]=useState<Record<string,unknown>>({...managementDefaults[resource],...(item??{})});
  const fields=managementFields[resource]; const mutation=useMutation({mutationFn:()=>item?apiClient.updateResource(resource,String(item.id),Object.fromEntries(Object.entries(values).filter(([key])=>key!=='id'&&(key!=='active'||resource==='users'||resource==='sla-rules')))):apiClient.createResource(resource,values),onSuccess:()=>{cache.invalidateQueries({queryKey:['management',resource]});cache.invalidateQueries({queryKey:['reference']});onClose();}});
  const options=(field:string)=>{if(field==='clientId')return refs.data?.clients.map(value=>({value:value.id,label:value.label}))??[];if(field==='demandTypeId')return refs.data?.demandTypes.map(value=>({value:value.id,label:value.name}))??[];if(field==='role')return (['CLIENT','SERVICE','TRAFFIC_MANAGER','ADMIN'] as Role[]).map(value=>({value,label:t(`role.${value}`)}));if(field==='scope')return ['DEFAULT','CLIENT','DEMAND_TYPE','CLIENT_AND_DEMAND_TYPE'].map(value=>({value,label:value}));return [];};
  const update=(key:string,value:unknown)=>setValues(current=>({...current,[key]:value}));
  if(refs.isPending)return <Dialog open><DialogContent><Loading/></DialogContent></Dialog>;
  return <Dialog open onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{t(item?'admin.edit':'admin.new')}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{fields.filter(field=>!(field.createOnly&&item)).map(field=>{const label=t(`admin.fields.${field.key}`);const value=values[field.key]??(field.type==='checkbox'?false:'');if(field.type==='checkbox')return <FormControl key={field.key}><Button variant={value?'contained':'outlined'} onClick={()=>update(field.key,!value)}>{label}: {value?'✓':'—'}</Button></FormControl>;if(field.type==='select')return <FormControl key={field.key}><InputLabel>{label}</InputLabel><Select label={label} value={String(value)} onChange={event=>update(field.key,event.target.value)}><MenuItem value="">—</MenuItem>{options(field.key).map(option=><MenuItem key={option.value} value={option.value}>{option.label}</MenuItem>)}</Select></FormControl>;return <TextField key={field.key} label={label} type={field.type==='textarea'?'text':field.type??'text'} multiline={field.type==='textarea'} minRows={field.type==='textarea'?3:undefined} value={String(value)} onChange={event=>update(field.key,event.target.value)} required={field.key!=='phone'&&field.key!=='clientId'&&field.key!=='demandTypeId'}/>;})}{mutation.isError&&<Failure/>}</Stack></DialogContent><DialogActions><Button onClick={onClose}>{t('actions.cancel')}</Button><Button variant="contained" onClick={()=>mutation.mutate()} disabled={mutation.isPending}>{t('actions.save')}</Button></DialogActions></Dialog>;
}
function ManagementPage({resource,titleKey}:{resource:string;titleKey:string}){const {t}=useTranslation();const cache=useQueryClient();const [editing,setEditing]=useState<Record<string,unknown>|null|undefined>(undefined);const [search,setSearch]=useState('');const query=useQuery({queryKey:['management',resource],queryFn:()=>apiClient.managementList(resource)});const toggle=useMutation({mutationFn:(item:Record<string,unknown>)=>apiClient.setResourceActive(resource,String(item.id),!Boolean(item.active)),onSuccess:()=>cache.invalidateQueries({queryKey:['management',resource]})});if(query.isPending)return <Loading/>;if(query.isError)return <Failure/>;const visible=query.data.filter(item=>JSON.stringify(item).toLocaleLowerCase().includes(search.toLocaleLowerCase()));return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Typography variant="h4" fontWeight={700}>{t(titleKey)}</Typography><Button variant="contained" onClick={()=>setEditing(null)}>{t('admin.new')}</Button></Stack><Card><CardContent><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField fullWidth label={t('actions.search')} value={search} onChange={event=>setSearch(event.target.value)}/><Button onClick={()=>setSearch('')}>{t('actions.clear')}</Button></Stack></CardContent></Card>{visible.length===0?<Alert severity="info">{t('tickets.noItems')}</Alert>:visible.map(item=><Card key={String(item.id)}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography fontWeight={700}>{String(item.name??item.email??item.id)}</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={1}>{Object.entries(item).filter(([key,value])=>!['id','name'].includes(key)&&value!==null&&typeof value!=='object').map(([key,value])=><Chip key={key} size="small" label={`${t(`admin.fields.${key}`)}: ${String(value)}`}/>)}</Stack></Box><Stack direction="row" gap={1}><Button onClick={()=>setEditing(item)}>{t('actions.open')}</Button>{typeof item.active==='boolean'&&resource!=='users'&&resource!=='sla-rules'&&<Button onClick={()=>toggle.mutate(item)}>{Boolean(item.active)?t('actions.cancel'):t('actions.open')}</Button>}</Stack></Stack></CardContent></Card>)}{editing!==undefined&&<ManagementDialog resource={resource} item={editing} onClose={()=>setEditing(undefined)}/>}</Stack>}
function ReportPage(){
  const {t}=useTranslation(); const [filters,setFilters]=useState<TicketFilters>({}); const refs=useQuery({queryKey:['reference'],queryFn:apiClient.reference}); const query=useQuery({queryKey:['report',filters],queryFn:()=>apiClient.reportTickets(filters)});
  const exportCsv=useMutation({mutationFn:()=>apiClient.exportTickets(filters),onSuccess:blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='sige-desk-tickets.csv';anchor.click();URL.revokeObjectURL(url);}});
  if(query.isPending||refs.isPending)return <Loading/>;if(query.isError||refs.isError)return <Failure error={query.error??refs.error}/>;
  const summary=query.data.summary;const average=summary.averageResolutionMinutes===null?t('reports.notAvailable'):`${summary.averageResolutionMinutes} ${t('reports.minutes')}`;
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Typography variant="h4" fontWeight={700}>{t('nav.reports')}</Typography><Button variant="outlined" onClick={()=>exportCsv.mutate()} disabled={exportCsv.isPending}>{t('actions.export')}</Button></Stack>{exportCsv.isError&&<Failure error={exportCsv.error}/>}<Card><CardContent><TicketFilterPanel filters={filters} onChange={setFilters} reference={refs.data}/></CardContent></Card><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:2}}>{[['active',summary.activeCount],['completed',summary.completedCount],['slaCompliant',`${summary.slaCompliantCount}/${summary.classifiedCount}`],['overdue',summary.overdueCount],['averageResolution',average]].map(([key,value])=><Card key={key}><CardContent><Typography color="text.secondary">{t(`reports.${key}`)}</Typography><Typography variant="h5" fontWeight={700}>{value}</Typography></CardContent></Card>)}</Box><TicketTable items={query.data.items}/></Stack>
}
function AppRoutes(){return <Routes><Route path="/login" element={<Login/>}/><Route element={<Layout/>}><Route path="/" element={<DashboardPage/>}/><Route path="/tickets" element={<TicketsPage/>}/><Route path="/tickets/new" element={<NewTicketPage/>}/><Route path="/tickets/:id" element={<TicketDetailPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/reports" element={<ReportPage/>}/><Route path="/clients" element={<ManagementPage resource="clients" titleKey="nav.clients"/>}/><Route path="/campaigns" element={<ManagementPage resource="campaigns" titleKey="nav.campaigns"/>}/><Route path="/demand-types" element={<ManagementPage resource="demand-types" titleKey="nav.demandTypes"/>}/><Route path="/sla" element={<ManagementPage resource="sla-rules" titleKey="nav.sla"/>}/><Route path="/users" element={<ManagementPage resource="users" titleKey="nav.users"/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
export function App(){return <ThemeProvider theme={theme}><AppRoutes/></ThemeProvider>}
