import {readFile,writeFile} from 'node:fs/promises';
const local = new URL('../../docs/openapi.yaml', import.meta.url);
const source=process.argv[2];
const api=source ? await (await fetch(source)).json() : JSON.parse(await readFile(local,'utf8'));
if(!api.openapi || !api.components?.schemas) throw new Error('OpenAPI inválido');
// JSON is also valid YAML 1.2. Keep one canonical contract without a YAML dependency.
if(source) api.servers=[{url:'http://localhost:8080',description:'Backend local'}];
if(source) await writeFile(local,JSON.stringify(api,null,2)+'\n');
const quote=JSON.stringify;
function type(s={}) {
 if(s.$ref) return 'ApiSchemas['+quote(s.$ref.split('/').at(-1))+']';
 if(s.enum) return s.enum.map(quote).join(' | ')+(Array.isArray(s.type)&&s.type.includes('null')?' | null':'');
 if(s.oneOf||s.anyOf) return '('+(s.oneOf??s.anyOf).map(type).join(' | ')+')';
 if(s.allOf) return '('+s.allOf.map(type).join(' & ')+')';
 if(Array.isArray(s.type)) return s.type.map(t=>type({...s,type:t})).join(' | ');
 if(s.type==='array') return '('+type(s.items)+')[]';
 if(s.type==='object'||s.properties) {const props=Object.entries(s.properties??{}).map(([k,v])=>quote(k)+(s.required?.includes(k)?'':'?')+': '+type(v)+';');if(s.additionalProperties) props.push('[key: string]: '+(s.additionalProperties===true?'unknown':type(s.additionalProperties))+';');return '{ '+props.join(' ')+' }';}
 return ({string:'string',integer:'number',number:'number',boolean:'boolean',null:'null'})[s.type]??'unknown';
}
const body='// Generated by pnpm api:sync. Do not edit.\nexport interface ApiSchemas {\n'+Object.entries(api.components.schemas).map(([name,s])=>'  '+quote(name)+': '+type(s)+';').join('\n')+'\n}\n';
await writeFile(new URL('../src/shared/api/generated.ts',import.meta.url),body);
console.log('Contrato sincronizado: '+Object.keys(api.paths).length+' rotas, '+Object.keys(api.components.schemas).length+' schemas.');
